sonar.projectKey=Joyeria-Diana-Laura
sonar.projectName=Joyeria-Diana-Laura
sonar.sources=.
# Esto reduce el reporte de 1GB a menos de 5MB
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.png,**/*.jpg,**/*.svg,**/coverage/**,.git/**