// Backend/src/models/importModel.ts
import pool from '../config/database';
import { CodeGenerator } from '../utils/codeGenerator';

export interface ImportResult {
  success: boolean;
  recordsProcessed: number;
  errors: string[];
  message: string;
}

export interface TableInfo {
  tableName: string;
  columns: string[];
  autoGeneratedColumns?: string[]; // Columnas que se generan automáticamente
}

// Columnas que deben excluirse de la importación (se generan automáticamente)
const AUTO_GENERATED_COLUMNS: { [key: string]: string[] } = {
  productos: ['id', 'codigo', 'fecha_creacion', 'fecha_actualizacion', 'categoria_nombre', 'proveedor_nombre'],
  categorias: ['id', 'fecha_creacion', 'fecha_actualizacion'],
  proveedores: ['id', 'fecha_creacion', 'fecha_actualizacion'],
  clientes: ['id', 'fecha_creacion', 'fecha_actualizacion'],
  temporadas: ['id', 'fecha_creacion', 'fecha_actualizacion'],
  tipos_producto: ['id', 'fecha_creacion'],
  promociones: ['id', 'usos_actuales', 'fecha_creacion', 'fecha_actualizacion'],
  metodos_pago: ['id', 'fecha_creacion', 'fecha_actualizacion'],
  preguntas_frecuentes: ['id', 'contador_util', 'fecha_creacion', 'fecha_actualizacion'],
  // ✅ NUEVO: Columnas auto-generadas para ventas
  ventas: [
    'id', 
    'fecha_creacion', 
    'fecha_actualizacion', 
    'total_articulos',  // Se calcula automáticamente por trigger
    'fecha_cancelacion',
    'cancelado_por',
    'motivo_cancelacion'
  ],
  // ✅ NUEVO: Columnas auto-generadas para detalle_ventas
  detalle_ventas: [
    'id',
    'fecha_creacion'
    // 'subtotal' se calcula automáticamente en bulkInsert
  ]
};

export const importModel = {
  
  // Obtener información de una tabla, incluyendo columnas auto-generadas
  async getTableInfo(tableName: string): Promise<TableInfo | null> {
    try {
      const query = `
        SELECT 
          column_name, 
          data_type,
          is_nullable,
          column_default
        FROM information_schema.columns 
        WHERE table_name = $1 
        ORDER BY ordinal_position
      `;
      
      const result = await pool.query(query, [tableName]);
      
      if (result.rows.length === 0) {
        return null;
      }
      
      // Identificar columnas auto-generadas (serial, identity, o con default)
      const autoGenerated = result.rows
        .filter(row => 
          row.column_default?.includes('nextval') || 
          AUTO_GENERATED_COLUMNS[tableName]?.includes(row.column_name)
        )
        .map(row => row.column_name);
      
      return {
        tableName,
        columns: result.rows.map(row => row.column_name),
        autoGeneratedColumns: autoGenerated
      };
    } catch (error) {
      console.error('Error getting table info:', error);
      throw error;
    }
  },

  // Obtener lista de tablas disponibles
  async getTables(): Promise<string[]> {
    try {
      const query = `
        SELECT table_name 
        FROM information_schema.tables 
        WHERE table_schema = 'public' 
        AND table_type = 'BASE TABLE'
        ORDER BY table_name
      `;
      
      const result = await pool.query(query);
      return result.rows.map(row => row.table_name);
    } catch (error) {
      console.error('Error getting tables:', error);
      throw error;
    }
  },

  // Insertar datos en lote con manejo de campos auto-generados
  async bulkInsert(tableName: string, columns: string[], data: any[][]): Promise<ImportResult> {
    const client = await pool.connect();
    const errors: string[] = [];
    let recordsProcessed = 0;
    
    try {
      await client.query('BEGIN');
      
      // Obtener información de la tabla para conocer columnas auto-generadas
      const tableInfo = await this.getTableInfo(tableName);
      const autoGenerated = tableInfo?.autoGeneratedColumns || [];
      
      // Filtrar columnas que no deben insertarse manualmente
      const insertableColumns = columns.filter(col => !autoGenerated.includes(col));
      
      if (insertableColumns.length === 0) {
        throw new Error('No hay columnas insertables (todas son auto-generadas)');
      }
      
      // Procesar cada fila individualmente para manejar generación de códigos
      for (let rowIndex = 0; rowIndex < data.length; rowIndex++) {
        try {
          const row = data[rowIndex];
          
          // Construir objeto con datos de la fila
          const rowData: any = {};
          columns.forEach((col, colIndex) => {
            if (!autoGenerated.includes(col)) {
              rowData[col] = row[colIndex];
            }
          });
          
          // ✅ GENERAR CÓDIGO para productos si no existe
          if (tableName === 'productos' && !rowData.codigo) {
            const categoriaId = rowData.categoria_id || 1;
            rowData.codigo = await CodeGenerator.generateProductCode(categoriaId, client);
          }
          
          // ✅ GENERAR FOLIO para ventas si no existe
          if (tableName === 'ventas' && !rowData.folio) {
            // Determinar fecha para el folio
            let fecha = new Date();
            if (rowData.fecha_creacion) {
              fecha = new Date(rowData.fecha_creacion);
            } else if (rowData.fecha_venta) {
              fecha = new Date(rowData.fecha_venta);
            }
            
            const fechaStr = fecha.toISOString().slice(0, 10).replace(/-/g, '');
            
            // Obtener último folio del día
            const lastFolio = await client.query(
              `SELECT folio FROM ventas WHERE folio LIKE $1 ORDER BY id DESC LIMIT 1`,
              [`VENTA-${fechaStr}-%`]
            );
            
            let nextNum = 1;
            if (lastFolio.rows.length > 0) {
              const match = lastFolio.rows[0].folio.match(/VENTA-\d+-(\d+)$/);
              if (match) nextNum = parseInt(match[1]) + 1;
            }
            
            rowData.folio = `VENTA-${fechaStr}-${String(nextNum).padStart(4, '0')}`;
          }
          
          // ✅ CALCULAR SUBTOTAL para detalle_ventas si no viene
          if (tableName === 'detalle_ventas') {
            if (!rowData.subtotal && rowData.cantidad && rowData.precio_unitario) {
              const cantidad = parseFloat(rowData.cantidad) || 0;
              const precio = parseFloat(rowData.precio_unitario) || 0;
              const descuento = parseFloat(rowData.descuento_unitario) || 0;
              rowData.subtotal = cantidad * (precio - descuento);
            }
            
            // Asegurar que personalizacion sea JSON válido
            if (rowData.personalizacion && typeof rowData.personalizacion === 'string') {
              try {
                // Si es string, intentar parsear
                rowData.personalizacion = JSON.parse(rowData.personalizacion);
              } catch (e) {
                // Si no es JSON válido, mantener como está o convertir a objeto vacío
                if (typeof rowData.personalizacion === 'string') {
                  rowData.personalizacion = { valor: rowData.personalizacion };
                }
              }
            }
          }
          
          // Construir INSERT dinámico
          const insertColumns = Object.keys(rowData);
          const placeholders = insertColumns.map((_, i) => `$${i + 1}`).join(', ');
          const values = Object.values(rowData);
          
          const insertQuery = `
            INSERT INTO ${tableName} (${insertColumns.join(', ')})
            VALUES (${placeholders})
            ON CONFLICT (id) DO NOTHING
            RETURNING id
          `;
          
          const result = await client.query(insertQuery, values);
          
          if (result.rows.length > 0) {
            recordsProcessed++;
            const insertedId = result.rows[0].id;
            
            // ✅ Si es detalle_ventas, actualizar total_articulos en ventas
            if (tableName === 'detalle_ventas' && rowData.venta_id) {
              await client.query(`
                UPDATE ventas 
                SET total_articulos = (
                  SELECT COALESCE(SUM(cantidad), 0) 
                  FROM detalle_ventas 
                  WHERE venta_id = $1
                ),
                fecha_actualizacion = CURRENT_TIMESTAMP
                WHERE id = $1
              `, [rowData.venta_id]);
            }
            
            // ✅ Si es venta, registrar historial de estado si se proporcionó estado
            if (tableName === 'ventas' && rowData.estado && rowData.estado !== 'pendiente') {
              await client.query(`
                INSERT INTO historial_estado_venta 
                (venta_id, estado_anterior, estado_nuevo, modificado_por)
                VALUES ($1, 'pendiente', $2, $3)
              `, [insertedId, rowData.estado, rowData.creado_por || 1]);
            }
          }
          
        } catch (rowError) {
          errors.push(`Fila ${rowIndex + 1}: ${rowError instanceof Error ? rowError.message : 'Error desconocido'}`);
        }
      }
      
      await client.query('COMMIT');
      
      return {
        success: errors.length === 0,
        recordsProcessed,
        errors,
        message: errors.length === 0 
          ? `✅ Se importaron ${recordsProcessed} registros en ${tableName} exitosamente`
          : `⚠️ Se importaron ${recordsProcessed} registros con ${errors.length} errores`
      };
      
    } catch (error) {
      await client.query('ROLLBACK');
      console.error('Error en bulk insert:', error);
      errors.push(error instanceof Error ? error.message : 'Error desconocido');
      
      return {
        success: false,
        recordsProcessed,
        errors,
        message: 'Error al importar los datos'
      };
    } finally {
      client.release();
    }
  },

  // Validar datos antes de insertar
  async validateData(tableName: string, data: any[]): Promise<{ valid: boolean; errors: string[] }> {
    const errors: string[] = [];
    
    try {
      const tableInfo = await this.getTableInfo(tableName);
      if (!tableInfo) {
        errors.push(`La tabla ${tableName} no existe`);
        return { valid: false, errors };
      }
      
      const autoGenerated = tableInfo.autoGeneratedColumns || [];
      
      // Validaciones básicas
      data.forEach((row, index) => {
        if (typeof row !== 'object' || row === null) {
          errors.push(`Fila ${index + 1}: formato inválido`);
          return;
        }
        
        // Validar que no se intenten insertar columnas auto-generadas
        Object.keys(row).forEach(key => {
          if (autoGenerated.includes(key) && row[key]) {
            errors.push(`Fila ${index + 1}: La columna '${key}' es auto-generada y no debe incluirse en el archivo`);
          }
        });
        
        // ✅ VALIDACIONES ESPECÍFICAS PARA VENTAS
        if (tableName === 'ventas') {
          // Validar estado
          const estadosValidos = ['pendiente', 'confirmado', 'en_preparacion', 'enviado', 'entregado', 'cancelado'];
          if (row.estado && !estadosValidos.includes(row.estado)) {
            errors.push(`Fila ${index + 1}: Estado inválido. Valores permitidos: ${estadosValidos.join(', ')}`);
          }
          
          // Validar que total sea numérico
          if (row.total && isNaN(parseFloat(row.total))) {
            errors.push(`Fila ${index + 1}: total debe ser un número`);
          }
          
          // Validar que subtotal sea numérico
          if (row.subtotal && isNaN(parseFloat(row.subtotal))) {
            errors.push(`Fila ${index + 1}: subtotal debe ser un número`);
          }
        }
        
        // ✅ VALIDACIONES ESPECÍFICAS PARA DETALLE_VENTAS
        if (tableName === 'detalle_ventas') {
          if (!row.venta_id) {
            errors.push(`Fila ${index + 1}: venta_id es obligatorio`);
          }
          
          if (row.venta_id && isNaN(parseInt(row.venta_id))) {
            errors.push(`Fila ${index + 1}: venta_id debe ser un número`);
          }
          
          if (!row.producto_id && !row.producto_codigo) {
            errors.push(`Fila ${index + 1}: Se requiere producto_id o producto_codigo`);
          }
          
          if (!row.cantidad) {
            errors.push(`Fila ${index + 1}: cantidad es obligatoria`);
          }
          
          if (row.cantidad && (parseInt(row.cantidad) <= 0 || isNaN(parseInt(row.cantidad)))) {
            errors.push(`Fila ${index + 1}: cantidad debe ser un número mayor a 0`);
          }
          
          if (!row.precio_unitario) {
            errors.push(`Fila ${index + 1}: precio_unitario es obligatorio`);
          }
          
          if (row.precio_unitario && (parseFloat(row.precio_unitario) <= 0 || isNaN(parseFloat(row.precio_unitario)))) {
            errors.push(`Fila ${index + 1}: precio_unitario debe ser un número mayor a 0`);
          }
        }
      });
      
      return {
        valid: errors.length === 0,
        errors
      };
    } catch (error) {
      errors.push(error instanceof Error ? error.message : 'Error de validación');
      return { valid: false, errors };
    }
  }
};