// Backend/src/models/importModel.ts
import pool from '../config/database';
import { CodeGenerator } from '../utils/codeGenerator';

export interface ImportResult {
  success: boolean;
  recordsProcessed: number;
  errors: string[];
  message: string;
}

export interface TableInfo {
  tableName: string;
  columns: string[];
  autoGeneratedColumns?: string[];
}

const AUTO_GENERATED_COLUMNS: { [key: string]: string[] } = {
  productos: ['id', 'codigo', 'fecha_creacion', 'fecha_actualizacion', 'categoria_nombre', 'proveedor_nombre'],
  categorias: ['id', 'fecha_creacion', 'fecha_actualizacion'],
  proveedores: ['id', 'fecha_creacion', 'fecha_actualizacion'],
  clientes: ['id', 'fecha_creacion', 'fecha_actualizacion'],
  temporadas: ['id', 'fecha_creacion', 'fecha_actualizacion'],
  tipos_producto: ['id', 'fecha_creacion'],
  promociones: ['id', 'usos_actuales', 'fecha_creacion', 'fecha_actualizacion'],
  metodos_pago: ['id', 'fecha_creacion', 'fecha_actualizacion'],
  preguntas_frecuentes: ['id', 'contador_util', 'fecha_creacion', 'fecha_actualizacion']
};

export const importModel = {
  
  async getTableInfo(tableName: string): Promise<TableInfo | null> {
    try {
      const query = `
        SELECT 
          column_name, 
          data_type,
          is_nullable,
          column_default
        FROM information_schema.columns 
        WHERE table_name = $1 
        ORDER BY ordinal_position
      `;
      
      const result = await pool.query(query, [tableName]);
      
      if (result.rows.length === 0) {
        return null;
      }
      
      const autoGenerated = result.rows
        .filter(row => 
          row.column_default?.includes('nextval') || 
          AUTO_GENERATED_COLUMNS[tableName]?.includes(row.column_name)
        )
        .map(row => row.column_name);
      
      return {
        tableName,
        columns: result.rows.map(row => row.column_name),
        autoGeneratedColumns: autoGenerated
      };
    } catch (error) {
      console.error('Error getting table info:', error);
      throw error;
    }
  },

  async getTables(): Promise<string[]> {
    try {
      const query = `
        SELECT table_name 
        FROM information_schema.tables 
        WHERE table_schema IN ('catalogo', 'ventas', 'configuracion', 'seguridad')
        AND table_type = 'BASE TABLE'
        ORDER BY table_name
      `;
      
      const result = await pool.query(query);
      return result.rows.map(row => row.table_name);
    } catch (error) {
      console.error('Error getting tables:', error);
      throw error;
    }
  },

  async bulkInsert(tableName: string, columns: string[], data: any[][]): Promise<ImportResult> {
    const client = await pool.connect();
    const errors: string[] = [];
    let recordsProcessed = 0;
    
    try {
      await client.query('BEGIN');
      
      const tableInfo = await this.getTableInfo(tableName);
      const autoGenerated = tableInfo?.autoGeneratedColumns || [];
      
      const insertableColumns = columns.filter(col => !autoGenerated.includes(col));
      
      if (insertableColumns.length === 0) {
        throw new Error('No hay columnas insertables (todas son auto-generadas)');
      }
      
      for (let rowIndex = 0; rowIndex < data.length; rowIndex++) {
        try {
          const row = data[rowIndex];
          
          const rowData: any = {};
          columns.forEach((col, colIndex) => {
            if (!autoGenerated.includes(col)) {
              rowData[col] = row[colIndex];
            }
          });
          
          // Determinar el esquema de la tabla
          let schema = '';
          if (tableName === 'productos' || tableName === 'categorias' || tableName === 'proveedores' || 
              tableName === 'temporadas' || tableName === 'tipos_producto') {
            schema = 'catalogo.';
          } else if (tableName === 'promociones' || tableName === 'metodos_pago') {
            schema = 'ventas.';
          } else if (tableName === 'preguntas_frecuentes') {
            schema = 'configuracion.';
          } else if (tableName === 'usuarios' || tableName === 'clientes') {
            schema = 'seguridad.';
          }
          
          if (tableName === 'productos' && !rowData.codigo) {
            const categoriaId = rowData.categoria_id || 1;
            rowData.codigo = await CodeGenerator.generateProductCode(categoriaId, client);
          }
          
          const insertColumns = Object.keys(rowData);
          const placeholders = insertColumns.map((_, i) => `$${i + 1}`).join(', ');
          const values = Object.values(rowData);
          
          const insertQuery = `
            INSERT INTO ${schema}${tableName} (${insertColumns.join(', ')})
            VALUES (${placeholders})
            ON CONFLICT DO NOTHING
            RETURNING id
          `;
          
          const result = await client.query(insertQuery, values);
          
          if (result.rows.length > 0) {
            recordsProcessed++;
          }
          
        } catch (rowError) {
          errors.push(`Fila ${rowIndex + 1}: ${rowError instanceof Error ? rowError.message : 'Error desconocido'}`);
        }
      }
      
      await client.query('COMMIT');
      
      return {
        success: errors.length === 0,
        recordsProcessed,
        errors,
        message: errors.length === 0 
          ? `✅ Se importaron ${recordsProcessed} registros en ${tableName} exitosamente`
          : `⚠️ Se importaron ${recordsProcessed} registros con ${errors.length} errores`
      };
      
    } catch (error) {
      await client.query('ROLLBACK');
      console.error('Error en bulk insert:', error);
      errors.push(error instanceof Error ? error.message : 'Error desconocido');
      
      return {
        success: false,
        recordsProcessed,
        errors,
        message: 'Error al importar los datos'
      };
    } finally {
      client.release();
    }
  },

  async validateData(tableName: string, data: any[]): Promise<{ valid: boolean; errors: string[] }> {
    const errors: string[] = [];
    
    try {
      const tableInfo = await this.getTableInfo(tableName);
      if (!tableInfo) {
        errors.push(`La tabla ${tableName} no existe`);
        return { valid: false, errors };
      }
      
      const autoGenerated = tableInfo.autoGeneratedColumns || [];
      
      data.forEach((row, index) => {
        if (typeof row !== 'object' || row === null) {
          errors.push(`Fila ${index + 1}: formato inválido`);
          return;
        }
        
        Object.keys(row).forEach(key => {
          if (autoGenerated.includes(key) && row[key]) {
            errors.push(`Fila ${index + 1}: La columna '${key}' es auto-generada y no debe incluirse en el archivo`);
          }
        });
      });
      
      return {
        valid: errors.length === 0,
        errors
      };
    } catch (error) {
      errors.push(error instanceof Error ? error.message : 'Error de validación');
      return { valid: false, errors };
    }
  }
};