// Backend/src/services/excelImportService.ts
import ExcelJS from 'exceljs';
import { importModel } from '../models/importModel';

export interface ExcelPreviewResult {
  headers: string[];
  data: any[];
  totalRows: number;
  warnings: string[];
}

export class ExcelImportService {
  
  /**
   * Procesa un archivo Excel y extrae los datos desde la fila 9
   */
  static async processExcel(filePath: string, tableName: string): Promise<ExcelPreviewResult> {
    const workbook = new ExcelJS.Workbook();
    await workbook.xlsx.readFile(filePath);
    
    // Obtener la hoja DATOS
    const worksheet = workbook.getWorksheet('DATOS');
    if (!worksheet) {
      throw new Error('El archivo Excel no contiene la hoja "DATOS"');
    }

    // Obtener información de la tabla para conocer columnas auto-generadas
    const tableInfo = await importModel.getTableInfo(tableName);
    const autoGeneratedColumns = tableInfo?.autoGeneratedColumns || [];
    
    // Obtener headers desde la fila 4
    const headerRow = worksheet.getRow(4);
    const headers: string[] = [];
    
    headerRow.eachCell((cell, colNumber) => {
      if (cell.value) {
        const headerName = cell.value.toString().trim();
        headers.push(headerName);
      }
    });

    if (headers.length === 0) {
      throw new Error('No se encontraron encabezados en la fila 4');
    }

    // Verificar si hay columnas auto-generadas en los headers
    const warnings: string[] = [];
    const autoGenInHeaders = headers.filter(h => autoGeneratedColumns.includes(h));
    if (autoGenInHeaders.length > 0) {
      warnings.push(`⚠️ Las siguientes columnas son auto-generadas y serán ignoradas: ${autoGenInHeaders.join(', ')}`);
    }

    // Filtrar headers para eliminar columnas auto-generadas
    const validHeaders = headers.filter(h => !autoGeneratedColumns.includes(h));

    // Leer datos desde la fila 9
    const data: any[] = [];
    let emptyRows = 0;
    const maxEmptyRows = 5;

    for (let rowNumber = 9; rowNumber <= worksheet.rowCount; rowNumber++) {
      const row = worksheet.getRow(rowNumber);
      
      let isEmpty = true;
      const rowData: any = {};
      
      validHeaders.forEach((header, index) => {
        // Encontrar el índice original de este header
        const originalIndex = headers.indexOf(header) + 1;
        const cell = row.getCell(originalIndex);
        let value = cell.value;
        
        if (value !== null && value !== undefined) {
          isEmpty = false;
          
          // Convertir según tipo
          if (value instanceof Date) {
            value = value.toISOString().split('T')[0];
          } else if (typeof value === 'object' && 'text' in value) {
            value = value.text;
          } else if (typeof value === 'number') {
            // Mantener números
          } else if (typeof value === 'boolean') {
            value = value ? 'TRUE' : 'FALSE';
          } else {
            value = value.toString().trim();
          }
          
          rowData[header] = value;
        } else {
          rowData[header] = null;
        }
      });

      if (isEmpty) {
        emptyRows++;
        if (emptyRows >= maxEmptyRows) {
          break;
        }
        continue;
      }

      emptyRows = 0;
      data.push(rowData);
    }

    if (data.length === 0) {
      throw new Error('No se encontraron datos en el archivo. Asegúrate de llenar a partir de la fila 9');
    }

    return {
      headers: validHeaders,
      data,
      totalRows: data.length,
      warnings
    };
  }
}