// Backend/src/services/exportService.ts
import ExcelJS from 'exceljs';
import pool from '../config/database';
import { FilterCondition, QueryBuilder } from '../utils/queryBuilder';

export interface ExportOptions {
  tableName: string;
  filters: FilterCondition[];
  includeRelations?: boolean;
  maxRows?: number;
}

export interface TableMetadata {
  columns: Array<{
    name: string;
    type: string;
    required: boolean;
    description: string;
    isUpdatable: boolean;
  }>;
  relations?: {
    [key: string]: Array<{ id: number; nombre: string }>;
  };
}

export class ExportService {
  
  static async getTableMetadata(tableName: string): Promise<TableMetadata> {
    try {
      const columnsQuery = `
        SELECT 
          column_name,
          data_type,
          is_nullable = 'NO' as is_required
        FROM information_schema.columns
        WHERE table_name = $1
        ORDER BY ordinal_position
      `;
      
      const columnsResult = await pool.query(columnsQuery, [tableName]);
      
      const autoGenerated = ['id', 'codigo', 'fecha_creacion', 'fecha_actualizacion', 
                            'categoria_nombre', 'proveedor_nombre', 'usos_actuales'];
      
      const columns = columnsResult.rows.map(col => ({
        name: col.column_name,
        type: this.mapDataType(col.data_type),
        required: col.is_required,
        description: this.getDefaultDescription(tableName, col.column_name),
        isUpdatable: !autoGenerated.includes(col.column_name)
      }));
      
      const relations: { [key: string]: Array<{ id: number; nombre: string }> } = {};
      
      if (tableName === 'productos') {
        const categorias = await pool.query(
          'SELECT id, nombre FROM categorias WHERE activo = true ORDER BY nombre'
        );
        relations['categorias'] = categorias.rows;
        
        const proveedores = await pool.query(
          'SELECT id, nombre FROM proveedores WHERE activo = true ORDER BY nombre'
        );
        relations['proveedores'] = proveedores.rows;
        
        const temporadas = await pool.query(
          'SELECT id, nombre FROM temporadas WHERE activo = true ORDER BY nombre'
        );
        relations['temporadas'] = temporadas.rows;
      }
      
      return { columns, relations };
      
    } catch (error) {
      console.error('❌ [ExportService] Error:', error);
      throw error;
    }
  }
  
  static async exportData(options: ExportOptions): Promise<ExcelJS.Workbook> {
    const { tableName, filters, includeRelations = false, maxRows = 10000 } = options;
    
    const { query, params } = QueryBuilder.buildSelectQuery({
      tableName,
      conditions: filters,
      limit: maxRows
    });
    
    const result = await pool.query(query, params);
    const data = result.rows;
    
    const workbook = new ExcelJS.Workbook();
    workbook.creator = 'Joyería Diana Laura';
    workbook.created = new Date();
    
    const metadata = await this.getTableMetadata(tableName);
    
    const dataSheet = workbook.addWorksheet('DATOS', {
      properties: { tabColor: { argb: 'FFECB2C3' } }
    });
    
    if (data.length > 0) {
      const headers = Object.keys(data[0]).filter(key => 
        !['id', 'fecha_creacion', 'fecha_actualizacion'].includes(key)
      );
      
      headers.forEach((header, index) => {
        const cell = dataSheet.getCell(4, index + 1);
        cell.value = header;
        cell.font = { bold: true };
        cell.fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: 'FF1A1A2E' }
        };
      });
      
      data.forEach((row, rowIndex) => {
        headers.forEach((header, colIndex) => {
          const cell = dataSheet.getCell(rowIndex + 7, colIndex + 1);
          cell.value = row[header] !== null && row[header] !== undefined ? String(row[header]) : '';
        });
        
        const idCell = dataSheet.getCell(rowIndex + 7, headers.length + 1);
        idCell.value = row.id;
        idCell.font = { color: { argb: 'FFFFFFFF' } };
      });
      
      headers.forEach((_, index) => {
        dataSheet.getColumn(index + 1).width = 20;
      });
    }
    
    return workbook;
  }
  
  private static mapDataType(pgType: string): string {
    const map: { [key: string]: string } = {
      'integer': 'número',
      'numeric': 'decimal',
      'varchar': 'texto',
      'text': 'texto',
      'boolean': 'booleano',
      'date': 'fecha',
      'timestamp': 'fecha/hora',
    };
    return map[pgType] || pgType;
  }
  
  private static getDefaultDescription(tableName: string, columnName: string): string {
    const descriptions: { [key: string]: { [key: string]: string } } = {
      productos: {
        nombre: 'Nombre del producto',
        categoria_id: 'ID de la categoría',
        precio_compra: 'Precio de compra',
        stock_actual: 'Stock actual',
      },
      proveedores: {
        nombre: 'Nombre del proveedor',
        email: 'Correo electrónico',
      }
    };
    return descriptions[tableName]?.[columnName] || columnName;
  }
}